// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClickableDivController from "./clickable_div_controller"
application.register("clickable-div", ClickableDivController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaypopupModalController from "./paypopup_modal_controller"
application.register("paypopup-modal", PaypopupModalController)
