// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BankAccountController from "./bank_account_controller"
application.register("bank-account", BankAccountController)

import ClickableDivController from "./clickable_div_controller"
application.register("clickable-div", ClickableDivController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import WidgetsController from "./widgets_controller"
application.register("widgets", WidgetsController)
